name: CI-teste
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'http://localhost:19999'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev novo
        
  deploy-hom:
    runs-on: ubuntu-latest
    environment:
      name: hom
      url: 'http://localhost:19988'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy hom

